### ISSUE TITLE
设置了前缀无法生效

### ISSUE THREAD

**Issue by Edward1108** [xiucaiwu/tp5redis#1]
在config文件中设置了前缀，但是缓存的键名没有前缀

**Comment by xiucaiwu** [comment]
紧急更新了一下,你看看是否凑效

**Comment by xiucaiwu** [comment]
紧急更新了一下,你看看是否凑效
















在 2020-05-22 11:41:16，"Edward" <notifications@github.com> 写道：

在config文件中设置了前缀，但是缓存的键名没有前缀

**Comment by xiucaiwu** [comment]
fix
